name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v2.4.0
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json tokens/input.json
      # Covert tokens according to Style Dictionary config
      - run: npx style-dictionary build --config config.json
      # Add files that were created during a run, e.g. created files from style dictionarty or token-transofrmer
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
      - run: git clone https://x-token-auth:ATCTT3xFfGN0namki89gwvIGFC15RDE1pq_ip9GLc3bLr-Bz3pFGAtgQkcwSIR-DPZl6NgaRGMAImom0XaGwuawM7p0lVUeAfir0_YUOUSgdD5AkS_KAG0-JVBmy2H_KwLyNIuMsNS0CFIQGItyy4Y8etfzpXEEodKQdfxivZ0nT7862opHAY-M=AC6F77B7@bitbucket.org/mbertonati-89/test-pipeline.git
      - run: git config user.email 6412283c1273131f2ae0da11@bots.bitbucket.org
      - run: git remote add bitbucket https://mbertonati@bitbucket.org/mbertonati-89/test-pipeline.git
      - run: git push bitbucket main