name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v2.4.0
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json tokens/input.json
      # Covert tokens according to Style Dictionary config
      - run: npx style-dictionary build --config config.json
      - run: git config user.email 6412283c1273131f2ae0da11@bots.bitbucket.org
      - run: git config --global user.name mbertonati
      - run: git remote add bitbucket https://mbertonati@bitbucket.org/mbertonati-89/test-pipeline.git
      - run: git add styles
      - run: git commit -m"Variables"
      - run: git push bitbucket main